TARGET = citypeep

SRCS = main.c gfx.c image.c system.c common.c input.c actor.c anim.c \
	   cp_memory.c save.c text.c menu.c sprite.c ninepatch.c audio.c \
	   dialogue.c camera.c

include ../actual_make.mk
